const PERIOD_LABELS = {
  daily: '每日热点',
  weekly: '一周热点',
  rising: '上升趋势热点',
  declining: '下降趋势仓库',
  search: '搜索结果',
};

export function exportMarkdown(repos, period) {
  const label = PERIOD_LABELS[period] || 'GitHub Trending';
  const date = new Date().toLocaleString('zh-CN');
  let md = `# ${label} (${date})\n\n`;
  md += `共 ${repos.length} 个仓库\n\n`;
  md += `| # | 仓库 | Stars | 语言 | 描述 |\n`;
  md += `|---|------|-------|------|------|\n`;
  repos.forEach((repo, i) => {
    const desc = (repo.description || '').replace(/\|/g, '\\|').slice(0, 80);
    md += `| ${i + 1} | [${repo.name}](${repo.url}) | ${(repo.stars || 0).toLocaleString()} | ${repo.language || ''} | ${desc} |\n`;
  });
  return md;
}

export function exportCSV(repos, period) {
  const label = PERIOD_LABELS[period] || 'GitHub Trending';
  const date = new Date().toLocaleString('zh-CN');
  let csv = `# ${label} - ${date}\n`;
  csv += '排名,仓库名,作者,Stars,语言,描述,URL\n';
  repos.forEach((repo, i) => {
    const desc = (repo.description || '').replace(/"/g, '""').slice(0, 100);
    csv += `${i + 1},"${repo.name}","${repo.author || ''}",${repo.stars},"${repo.language || ''}","${desc}","${repo.url}"\n`;
  });
  return '\uFEFF' + csv;
}

export function exportJSON(repos, period) {
  const exportData = {
    exportTime: new Date().toISOString(),
    period,
    periodLabel: PERIOD_LABELS[period] || 'GitHub Trending',
    total: repos.length,
    repos: repos.map((r) => ({
      name: r.name,
      author: r.author,
      repo_name: r.repo_name,
      url: r.url,
      stars: r.stars,
      language: r.language,
      description: r.description,
      topics: r.topics || [],
      period: r.period,
    })),
  };
  return JSON.stringify(exportData, null, 2);
}

export function exportHTML(repos, period) {
  const label = PERIOD_LABELS[period] || 'GitHub Trending';
  const date = new Date().toLocaleString('zh-CN');
  const reposJSON = JSON.stringify(repos);

  return `<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${label} - GitHub Trending</title>
<style>
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#f5f5f5;color:#333;min-height:100vh}
.header{background:#fff;padding:16px 24px;box-shadow:0 2px 8px rgba(0,0,0,.06);position:sticky;top:0;z-index:100}
.header h1{font-size:20px;font-weight:700;display:flex;align-items:center;gap:8px}
.header .sub{font-size:13px;color:#888;margin-top:4px}
.container{max-width:1200px;margin:0 auto;padding:24px 20px}
.repo-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(320px,1fr));gap:16px}
.repo-card{background:#fff;border-radius:10px;border:1px solid #f0f0f0;padding:18px;transition:all .2s;cursor:pointer;display:flex;flex-direction:column}
.repo-card:hover{border-color:#1677ff;box-shadow:0 4px 12px rgba(22,119,255,.1);transform:translateY(-2px)}
.repo-card .name{font-size:15px;font-weight:600;color:#1677ff;margin-bottom:6px;word-break:break-all}
.repo-card .desc{font-size:12px;color:#666;margin-bottom:8px;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}
.repo-card .tags{display:flex;flex-wrap:wrap;gap:4px;margin-bottom:6px}
.repo-card .tag{font-size:10px;padding:2px 6px;background:#f0f0f0;border-radius:4px;color:#888}
.repo-card .meta{display:flex;justify-content:space-between;align-items:center;margin-top:auto;padding-top:10px;border-top:1px solid #f5f5f5;font-size:12px;color:#999}
.repo-card .meta .stars{color:#f5a623;font-weight:600;font-size:13px}
.repo-card .rank{position:absolute;top:8px;right:12px;font-size:24px;font-weight:800;color:#f0f0f0}
.repo-card{position:relative}
.empty{text-align:center;padding:60px;color:#999;font-size:14px}
.footer{text-align:center;padding:20px;color:#bbb;font-size:12px}
@media(max-width:768px){.repo-grid{grid-template-columns:1fr}}
</style>
</head>
<body>
<div class="header">
  <h1>\u{1F4CA} ${label}</h1>
  <div class="sub">\u{1F4C5} ${date} &nbsp;|&nbsp; 共 ${repos.length} 个仓库 &nbsp;|&nbsp; \u{1F4E4} 自包含离线文件</div>
</div>
<div class="container">
  <div class="repo-grid" id="repoGrid"></div>
  <div class="footer">Generated by GitHub Trending Viewer &middot; Open Source</div>
</div>
<script>
var repos = ${reposJSON};
var grid = document.getElementById('repoGrid');
if (!repos.length) {
  grid.innerHTML = '<div class="empty">\u{1F4AD} 暂无数据</div>';
} else {
  repos.forEach(function(repo, i) {
    var card = document.createElement('div');
    card.className = 'repo-card';
    card.onclick = function() { window.open(repo.url, '_blank'); };
    var topics = (repo.topics || []).slice(0, 5).map(function(t) {
      return '<span class="tag">' + t + '</span>';
    }).join('');
    if ((repo.topics || []).length > 5) topics += '<span class="tag">+' + (repo.topics.length - 5) + '</span>';
    card.innerHTML =
      '<div class="rank">' + (i + 1) + '</div>' +
      '<div class="name">' + repo.name + '</div>' +
      (repo.description ? '<div class="desc">' + repo.description + '</div>' : '') +
      (topics ? '<div class="tags">' + topics + '</div>' : '') +
      '<div class="meta">' +
        '<span>' + (repo.language || '') + '</span>' +
        '<span class="stars">\u2B50 ' + (repo.stars || 0).toLocaleString() + '</span>' +
      '</div>';
    grid.appendChild(card);
  });
}
</script>
</body>
</html>`;
}

export function downloadFile(content, filename) {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function copyToClipboard(content) {
  if (navigator.clipboard) {
    return navigator.clipboard.writeText(content);
  }
  const textarea = document.createElement('textarea');
  textarea.value = content;
  textarea.style.position = 'fixed';
  textarea.style.opacity = '0';
  document.body.appendChild(textarea);
  textarea.select();
  document.execCommand('copy');
  document.body.removeChild(textarea);
  return Promise.resolve();
}